#!/bin/sh

LANG=C
LANGUAGE=C
LC_ALL=C

dpkg-buildpackage -b -us -uc 2>&1 | tee build.log

ls ../*.deb &> /dev/null

if [ $? = 0 ] ; then
	for f in ../*.deb ; do
		echo "$f:"
		dpkg-deb -I $f
		echo ""
	done 2>&1 | tee -a build.log
	for f in ../*.deb ; do
		echo "$f:"
		dpkg-deb -c $f
		echo ""
	done 2>&1 | tee -a build.log
	for f in ../*.deb ; do
		echo "$f:"
		lintian $f
		echo ""
	done 2>&1 | tee -a build.log
fi
