#!/bin/sh

LANG=C
LANGUAGE=C
LC_ALL=C

dpkg-buildpackage -j`nproc` -rfakeroot -b -us -uc 2>&1 | tee build.log

packages="$(find .. -maxdepth 1 -type f -name *.deb)"

if [ -n "$packages" ]; then
	for f in $packages ; do
		echo "$f:"
		dpkg-deb -I $f
		echo ""
	done 2>&1 | tee -a build.log
	for f in $packages ; do
		echo "$f:"
		dpkg-deb -c $f
		echo ""
	done 2>&1 | tee -a build.log
	if [ -x /usr/bin/lintian ]; then
		for f in $packages ; do
			echo "$f:"
			lintian $f
			echo ""
		done 2>&1 | tee -a build.log
	fi
fi

