#!/bin/sh

# sed -e 's/^[ \t]*//;s/[ \t]*$//' -e '/^#/d' -e '/^$/d'

if [ -z $1 ]; then exit 0; else true; fi
xz -kf9 $1
printf '#!/bin/sh\nx=`tempfile`;echo ' > ${1}-min
base64 -w 0 ${1}.xz >> ${1}-min
printf '|base64 -d|xz -d>$x && chmod +x $x && $x $@; rm $x' >> ${1}-min
rm -f ${1}.xz
chmod a+x ${1}-min
