#!/bin/sh

set -e

# minimum required build-dependencies: git build-essential libx11-dev pkg-config yasm zlib1g-dev


export CFLAGS="-O3 -fstack-protector --param=ssp-buffer-size=4 -D_FORTIFY_SOURCE=2"
export CXXFLAGS="-O3 -fstack-protector --param=ssp-buffer-size=4 -D_FORTIFY_SOURCE=2"
export LDFLAGS="-Wl,-Bsymbolic-functions -Wl,-z,relro -Wl,-z,noexecstack -Wl,--as-needed"
prefix="$PWD/ffmpeg-source/libs"


echo "downloading sources..."
git clone --depth 1 git://git.videolan.org/x264.git x264-source
git clone --depth 1 git://git.code.sf.net/p/opencore-amr/fdk-aac fdk-aac-source
git clone --depth 1 git://source.ffmpeg.org/ffmpeg.git ffmpeg-source


echo "build fdk-aac static library..."
cd fdk-aac-source
./autogen.sh
./configure --prefix="$prefix" --enable-static=yes --enable-shared=no
make
make install


echo "build x264 static library..."
cd ../x264-source
./configure --prefix="$prefix" --bit-depth=8 --chroma-format=all --disable-cli --enable-static --enable-strip \
            --disable-opencl --disable-avs --disable-swscale --disable-lavf --disable-ffms --disable-gpac --disable-lsmash
make
make install


echo "build ffmpeg"
cd ../ffmpeg-source
./configure --disable-debug --disable-ffplay --disable-ffprobe --disable-ffserver --disable-doc \
            --enable-gpl --enable-libx264 --enable-nonfree --enable-libfdk-aac \
			--extra-cflags="-I./libs/include" --extra-ldflags="-L./libs/lib"
make
cp ffmpeg ..
strip ../ffmpeg
echo "ffmpeg successfully built"

