#!/bin/sh

set -e

export CFLAGS="-fstack-protector --param=ssp-buffer-size=4 -Wformat -D_FORTIFY_SOURCE=2"
export CXXFLAGS="$CFLAGS"


cd ffmpeg-2.?.?/
make distclean || true


# no fpic
# enable GPL for libpostproc
./configure --prefix=$HOME/ffmpeg-static --enable-gpl \
	--disable-debug --enable-small --disable-runtime-cpudetect \
	--disable-programs --disable-doc --disable-dxva2 --disable-vaapi --disable-vda --disable-vdpau \
	--enable-avresample --enable-avisynth --disable-bzlib --disable-lzma
make
make install


make distclean


# with fpic
# enable GPL for libpostproc
./configure --prefix=$HOME/ffmpeg-static-fpic --enable-gpl \
	--disable-debug --enable-pic --enable-small --disable-runtime-cpudetect \
	--disable-programs --disable-doc --disable-dxva2 --disable-vaapi --disable-vda --disable-vdpau \
	--enable-avresample --enable-avisynth --disable-bzlib --disable-lzma
make
make install

