#!/bin/sh

help() {
   echo "usage: $(basename ${0}) <file>"
   echo "       $(basename ${0}) -c <checksum> <file>"
   exit 0
}

if [ -z "${1}" ]; then
   help
fi

if [ "${1}" = "-c" ] ; then
   if [ -z "${2}" ] || [ -z "${3}" ] ; then
      help
   else
      if [ "${2}" = `$(basename ${0})sum -b "${3}" | cut -d' ' -f1` ] ; then
         echo "OK"
         exit 0
      else
         echo "MISMATCH"
         exit 1
      fi
   fi
fi

$(basename ${0})sum -b "${1}" | cut -d' ' -f1
