#!/bin/sh

set -e

# repack-deb - Repack Debian package with xz compression algorithm

# print usage
if [ -z "$1" ] ; then
  echo "Repack Debian package with xz compression."
  echo "Usage: $0 file.deb"
  exit 0
fi

# check if it's a file
if [ ! -f "$1" ] ; then
  echo "'$1' is not a file"
  exit 1
fi

# check for xz compression
if [ ! -z $(ar t "$1" | grep -e data.tar.xz) ] ; then
  echo "'$1' is already xz compressed"
  exit 0
fi


# extract .deb
echo "extract '$1'"
ar x "$1"


# backup .deb
echo "move '$1' to '${1}.old'"
mv "$1" "$1".old


# uncompress data.tar
d=data.tar
echo "uncompress '`ls ${d}.*`'"

if [ -f ${d}.gz ] ; then
  gunzip -f ${d}.gz
elif [ -f ${d}.bz2 ] ; then
  bunzip2 -f ${d}.bz2
elif [ -f ${d}.lzma ] ; then
  unlzma -f ${d}.lzma
fi


# compress data.tar
echo "compress (xz) '$d'"
xz $d


# create new .deb and remove temporary files

files="debian-binary control.tar.gz ${d}.xz"

echo "create '$1'"
ar rc "$1" $files

echo "remove temporary files"
rm -f $files
