#!/bin/sh

steamdir="$HOME/.local/share/Steam/"

find "$steamdir" -type f -executable | sed -e 's/ /__SPACEHOLDER__/g'> /tmp/filelist.tmp
grep -e '\.so' /tmp/filelist.tmp > /tmp/sharedobjs.tmp
grep -v -e '\.so' /tmp/filelist.tmp > /tmp/nonsharedobjs.tmp

for f in $(cat /tmp/sharedobjs.tmp) ; do
    g="$(echo $f | sed -e 's/__SPACEHOLDER__/ /g')"
    echo "chmod 0644: "$(echo "$g" | sed -e "s@$steamdir@@")
    chmod 0644 "$g";
done

for f in $(cat /tmp/nonsharedobjs.tmp) ; do
    g="$(echo $f | sed -e 's/__SPACEHOLDER__/ /g')"
    if [ "`file -b "$g" | grep -e "text executable"`" ] || \
       [ "`file -b "$g" | grep -e "ELF"`" ]; then
        echo "chmod 0755: "$(echo "$g" | sed -e "s@$steamdir@@")
        chmod 0755 "$g";
    else
        echo "chmod 0644: "$(echo "$g" | sed -e "s@$steamdir@@")
        chmod 0644 "$g";
    fi
done

