#!/bin/sh

rm -rf x265-source
hg clone https://bitbucket.org/multicoreware/x265 x265-source
cd x265-source

LT=$(hg parents --template '{latesttag}')
LTD=$(hg parents --template '{latesttagdistance}')
NODE=$(hg parents --template '{node|short}')
VERSION=${LT}+${LTD}+hg${NODE}

sed -i "s/set(X265_VERSION \"unknown\")/set(X265_VERSION \"${VERSION}\")/;" source/cmake/version.cmake
sed -i "s/set(X265_LATEST_TAG \"0.0\")/set(X265_LATEST_TAG \"${LT}\")/;" source/cmake/version.cmake
sed -i "s/set(X265_TAG_DISTANCE \"0\")/set(X265_TAG_DISTANCE \"${LTD}\")/;" source/cmake/version.cmake
rm -rf .hg .hgignore .hgtags

cd ..
mv x265-source x265-${VERSION}
find x265-${VERSION} -type d -empty -delete

tar -cJf "x265_${VERSION}.orig.tar.xz" "x265-${VERSION}/"

