#!/bin/sh

rm -rf x265-source
hg clone https://bitbucket.org/multicoreware/x265 x265-source
cd x265-source && hg checkout stable

VERSION=$(hg parents --template '{latesttag}')

sed -i "s/set(X265_VERSION \"unknown\")/set(X265_VERSION \"${VERSION}\")/;" source/cmake/version.cmake
sed -i "s/set(X265_LATEST_TAG \"0.0\")/set(X265_LATEST_TAG \"${VERSION}\")/;" source/cmake/version.cmake
rm -rf .hg .hgignore .hgtags

cd ..
mv x265-source x265-${VERSION}
find x265-${VERSION} -type d -empty -delete

tar -cJf "x265_${VERSION}.orig.tar.xz" "x265-${VERSION}/"

